name: Release - Docker Image CI

on:
  release:
    branches: [ master ]
    types: [ published ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "call action"
        id: last_release
        uses: pozetroninc/github-action-get-latest-release@v0.7.0
        with:
          owner: jam2jam 
          repo: Docker-7DaysToDie
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4.1.1
        with:
          push: true
          tags: |
            jam2jam/7dtd-server:latest,jam2jam/7dtd-server:${{ steps.last_release.outputs.release }}
